[package]
name = "rust-avec-sdl"
version = "0.1.0"
authors = ["Christian Hutslar <cjhutslar@att.net>"]

[lib]
name = "ras"
path = "src/lib.rs"

[[bin]]
name = "rust-avec-sdl"
path = "src/main.rs"

[dependencies]
sdl2 = "0.31"
sdl2-sys = "0.31"
gl = "0.6"
png = "0.12"
